apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-{{ .Values.resourceName }}
spec:
  ports:
    - port: 3306
  selector:
    tier: mysql-{{ .Values.resourceName }}
  type: ClusterIP 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-{{ .Values.resourceName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-{{ .Values.resourceName }}
spec:
  selector:
    matchLabels:
      tier: mysql-{{ .Values.resourceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: mysql-{{ .Values.resourceName }}
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim-{{ .Values.resourceName }}
